// Deploys RailSplitPay and seeds a few payment links so the dashboard has
// real on-chain data to read. Run with:
//   npx hardhat run scripts/deploy.js --network coston2
const { existsSync, readFileSync, writeFileSync, mkdirSync } = require("node:fs");
const { join, dirname } = require("node:path");
const { JsonRpcProvider, Wallet, ContractFactory, formatEther } = require("ethers");
const { readEnvValue } = require("./read-env");
const { resolveFtsoV2Address } = require("./resolve-ftso-v2");

const RPC_URL = "https://coston2-api.flare.network/ext/C/rpc";
const EXPLORER = "https://coston2-explorer.flare.network";

const artifactPath = join(
  __dirname,
  "..",
  "artifacts",
  "contracts",
  "RailSplitPay.sol",
  "RailSplitPay.json",
);

// Links seeded at deploy time. Prices are in US cents.
//
// These are deliberately tiny. FLR trades near $0.006 on Coston2, so one
// dollar costs about 160 C2FLR, and the faucet hands out roughly 100. Prices
// this small keep every seeded link payable from a single faucet claim.
const seedLinks = [
  { slug: "arcade-run-001", title: "Arcade Run 001", priceUsdCents: 25 },
  { slug: "studio-retainer-july", title: "July studio retainer", priceUsdCents: 10 },
  { slug: "archive-print-release", title: "Archive print release", priceUsdCents: 5 },
];

async function main() {
  const key = readEnvValue("DEPLOYER_PRIVATE_KEY");

  if (!key) {
    throw new Error("No DEPLOYER_PRIVATE_KEY. Run: node scripts/new-wallet.js");
  }

  if (!existsSync(artifactPath)) {
    throw new Error("No compiled artifact. Run: npx hardhat compile");
  }

  const provider = new JsonRpcProvider(RPC_URL, 114);
  const wallet = new Wallet(key, provider);
  const balance = await provider.getBalance(wallet.address);

  console.log("Deployer: " + wallet.address);
  console.log("Balance:  " + formatEther(balance) + " C2FLR");

  if (balance === 0n) {
    throw new Error(
      "Deployer has no C2FLR. Fund " +
        wallet.address +
        " at https://faucet.flare.network/coston2",
    );
  }

  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const factory = new ContractFactory(artifact.abi, artifact.bytecode, wallet);

  // Resolve the FLR/USD feed for this network from the Flare contract
  // registry, then pass it in so the contract has no network-specific import.
  const ftsoV2Address = await resolveFtsoV2Address(provider);

  console.log("");
  console.log("Deploying RailSplitPay...");
  console.log("FTSOv2 feed:  " + ftsoV2Address);

  const contract = await factory.deploy(ftsoV2Address);
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  const deployTx = contract.deploymentTransaction();

  console.log("Deployed to: " + address);
  console.log("Tx:          " + EXPLORER + "/tx/" + deployTx.hash);

  // Confirm the FTSO feed reads before seeding, so a broken oracle wiring
  // shows up here rather than at a customer's checkout.
  const [feedValue, feedDecimals, feedTimestamp] = await contract.flrUsdFeed();
  const price = Number(feedValue) / 10 ** Number(feedDecimals);
  console.log("");
  console.log("FTSO FLR/USD: " + price.toFixed(6) + " USD");
  console.log("  raw value:  " + feedValue.toString());
  console.log("  decimals:   " + feedDecimals.toString());
  console.log("  timestamp:  " + feedTimestamp.toString());

  console.log("");
  console.log("Seeding payment links...");

  for (const link of seedLinks) {
    const tx = await contract.createPaymentLink(
      link.slug,
      link.title,
      link.priceUsdCents,
      0,
    );
    await tx.wait();

    const [requiredWei] = await contract.quote(link.slug);
    console.log(
      "  " +
        link.slug.padEnd(24) +
        "$" +
        (link.priceUsdCents / 100).toFixed(2).padStart(9) +
        "  =  " +
        Number(formatEther(requiredWei)).toFixed(4) +
        " C2FLR",
    );
  }

  // Write the deployed address where the Next.js app can import it. The ABI
  // lives in its own generated module, written by scripts/write-abi.js.
  const outPath = join(__dirname, "..", "..", "src", "lib", "contract-address.ts");
  mkdirSync(dirname(outPath), { recursive: true });

  writeFileSync(
    outPath,
    "// Generated by contracts/scripts/deploy.js. Do not edit by hand.\n" +
      "// Deployed " +
      new Date().toISOString() +
      " to Flare Testnet Coston2 (chain 114).\n\n" +
      "export const RAILSPLIT_PAY_ADDRESS =\n  \"" +
      address +
      "\" as const;\n" +
      "\nexport const DEMO_SLUG = \"" +
      seedLinks[0].slug +
      "\" as const;\n",
    "utf8",
  );

  console.log("");
  console.log("Wrote address to src/lib/contract-address.ts");
  console.log("Contract: " + EXPLORER + "/address/" + address);
}

main().catch((error) => {
  console.error(error.message || error);
  process.exitCode = 1;
});
