// Deploys RailSplitPayXrp and seeds a few payment links for the XRPL EVM
// Testnet flow. Run with:
//   npx hardhat run scripts/deploy-xrp.js --network xrplevmTestnet
const { readFileSync, writeFileSync, existsSync, mkdirSync } = require("node:fs");
const { join, dirname } = require("node:path");
const { JsonRpcProvider, Wallet, ContractFactory, formatEther } = require("ethers");
const { readEnvValue } = require("./read-env");

const RPC_URL = readEnvValue("XRP_RPC_URL") || readEnvValue("XRPL_EVM_RPC_URL") || "https://rpc.testnet.xrplevm.org";
const EXPLORER = readEnvValue("XRP_EXPLORER_URL") || "https://explorer.testnet.xrplevm.org";

const artifactPath = join(
  __dirname,
  "..",
  "artifacts",
  "contracts",
  "RailSplitPayXrp.sol",
  "RailSplitPayXrp.json",
);

const seedLinks = [
  { slug: "arcade-run-001", title: "Arcade Run 001", priceUsdCents: 25 },
  { slug: "studio-retainer-july", title: "July studio retainer", priceUsdCents: 10 },
  { slug: "archive-print-release", title: "Archive print release", priceUsdCents: 5 },
];

async function main() {
  const deployerKey = readEnvValue("XRP_DEPLOYER_PRIVATE_KEY") || readEnvValue("DEPLOYER_PRIVATE_KEY");
  if (!deployerKey) {
    throw new Error("No DEPLOYER_PRIVATE_KEY. Run: node scripts/new-wallet.js");
  }

  const quoteSignerKey = readEnvValue("XRP_QUOTE_SIGNER_PRIVATE_KEY") || deployerKey;

  if (!existsSync(artifactPath)) {
    throw new Error("No compiled artifact. Run: npx hardhat compile");
  }

  const provider = new JsonRpcProvider(RPC_URL, 1449000);
  const wallet = new Wallet(deployerKey, provider);
  const quoteSigner = new Wallet(quoteSignerKey, provider);
  const balance = await provider.getBalance(wallet.address);

  console.log("Deployer:     " + wallet.address);
  console.log("Quote signer: " + quoteSigner.address);
  console.log("Balance:      " + formatEther(balance) + " XRP");

  if (balance === 0n) {
    throw new Error(
      "Deployer has no XRP. Fund " + wallet.address + " with the XRPL EVM faucet at https://faucet.xrplevm.org",
    );
  }

  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const factory = new ContractFactory(artifact.abi, artifact.bytecode, wallet);

  console.log("");
  console.log("Deploying RailSplitPayXrp...");

  const contract = await factory.deploy(quoteSigner.address);
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  const deployTx = contract.deploymentTransaction();

  console.log("Deployed to: " + address);
  console.log("Tx:          " + EXPLORER + "/tx/" + deployTx.hash);

  console.log("");
  console.log("Seeding payment links...");

  for (const link of seedLinks) {
    const tx = await contract.createPaymentLink(link.slug, link.title, link.priceUsdCents, 0);
    await tx.wait();

    console.log(
      "  " +
        link.slug.padEnd(24) +
        "$" +
        (link.priceUsdCents / 100).toFixed(2).padStart(9) +
        "  seeded",
    );
  }

  const outPath = join(__dirname, "..", "..", "src", "lib", "xrp-contract-address.ts");
  mkdirSync(dirname(outPath), { recursive: true });

  writeFileSync(
    outPath,
    "// Generated by contracts/scripts/deploy-xrp.js. Do not edit by hand.\n\n" +
      "export const XRPL_EVM_PAY_ADDRESS =\n  \"" +
      address +
      "\" as const;\n",
    "utf8",
  );

  console.log("");
  console.log("Wrote address to src/lib/xrp-contract-address.ts");
  console.log("Contract: " + EXPLORER + "/address/" + address);
}

main().catch((error) => {
  console.error(error.message || error);
  process.exitCode = 1;
});
