// Generated by contracts/scripts/deploy.js. Do not edit by hand.
// Deployed 2026-08-14T16:03:29.399Z to Flare Testnet Coston2 (chain 114).

export const RAILSPLIT_PAY_ADDRESS =
  "0x3f504e17143a9A10eB9D3B879d7e85EC54fA57fa" as const;

export const DEMO_SLUG = "arcade-run-001" as const;
