// Generated by contracts/scripts/deploy.js. Do not edit by hand.
// Deployed 2026-08-11T15:48:15.239Z to Flare Testnet Coston2 (chain 114).

export const RAILSPLIT_PAY_ADDRESS =
  "0x1DBC6ECbF79Cb163555a5776A9b10aab5e6b9296" as const;

export const DEMO_SLUG = "arcade-run-001" as const;
