export const RAILSPLIT_PAY_XRP_ABI = [
  {
    type: "constructor",
    inputs: [{ name: "quoteSigner_", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createPaymentLink",
    stateMutability: "nonpayable",
    inputs: [
      { name: "slug", type: "string", internalType: "string" },
      { name: "title", type: "string", internalType: "string" },
      { name: "priceUsdCents", type: "uint64", internalType: "uint64" },
      { name: "expiresAt", type: "uint64", internalType: "uint64" },
    ],
    outputs: [{ name: "linkId", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "function",
    name: "pay",
    stateMutability: "payable",
    inputs: [
      { name: "slug", type: "string", internalType: "string" },
      { name: "xrpUsdPrice", type: "uint256", internalType: "uint256" },
      { name: "issuedAt", type: "uint64", internalType: "uint64" },
      { name: "validUntil", type: "uint64", internalType: "uint64" },
      { name: "signature", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "quote",
    stateMutability: "view",
    inputs: [
      { name: "slug", type: "string", internalType: "string" },
      { name: "xrpUsdPrice", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "requiredWei", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "quoteUsdCents",
    stateMutability: "pure",
    inputs: [
      { name: "priceUsdCents", type: "uint64", internalType: "uint64" },
      { name: "xrpUsdPrice", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "requiredWei", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "getPaymentLink",
    stateMutability: "view",
    inputs: [{ name: "slug", type: "string", internalType: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct RailSplitPayXrp.PaymentLink",
        components: [
          { name: "merchant", type: "address", internalType: "address" },
          { name: "priceUsdCents", type: "uint64", internalType: "uint64" },
          { name: "createdAt", type: "uint64", internalType: "uint64" },
          { name: "expiresAt", type: "uint64", internalType: "uint64" },
          { name: "active", type: "bool", internalType: "bool" },
          { name: "paymentCount", type: "uint32", internalType: "uint32" },
          { name: "totalReceivedWei", type: "uint256", internalType: "uint256" },
          { name: "totalReceivedUsdCents", type: "uint64", internalType: "uint64" },
          { name: "title", type: "string", internalType: "string" },
          { name: "slug", type: "string", internalType: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getPaymentLinkById",
    stateMutability: "view",
    inputs: [{ name: "linkId", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct RailSplitPayXrp.PaymentLink",
        components: [
          { name: "merchant", type: "address", internalType: "address" },
          { name: "priceUsdCents", type: "uint64", internalType: "uint64" },
          { name: "createdAt", type: "uint64", internalType: "uint64" },
          { name: "expiresAt", type: "uint64", internalType: "uint64" },
          { name: "active", type: "bool", internalType: "bool" },
          { name: "paymentCount", type: "uint32", internalType: "uint32" },
          { name: "totalReceivedWei", type: "uint256", internalType: "uint256" },
          { name: "totalReceivedUsdCents", type: "uint64", internalType: "uint64" },
          { name: "title", type: "string", internalType: "string" },
          { name: "slug", type: "string", internalType: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "linkCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "getLinks",
    stateMutability: "view",
    inputs: [
      { name: "offset", type: "uint256", internalType: "uint256" },
      { name: "limit", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "page",
        type: "tuple[]",
        internalType: "struct RailSplitPayXrp.PaymentLink[]",
        components: [
          { name: "merchant", type: "address", internalType: "address" },
          { name: "priceUsdCents", type: "uint64", internalType: "uint64" },
          { name: "createdAt", type: "uint64", internalType: "uint64" },
          { name: "expiresAt", type: "uint64", internalType: "uint64" },
          { name: "active", type: "bool", internalType: "bool" },
          { name: "paymentCount", type: "uint32", internalType: "uint32" },
          { name: "totalReceivedWei", type: "uint256", internalType: "uint256" },
          { name: "totalReceivedUsdCents", type: "uint64", internalType: "uint64" },
          { name: "title", type: "string", internalType: "string" },
          { name: "slug", type: "string", internalType: "string" },
        ],
      },
      { name: "total", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    name: "paymentCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "getPayments",
    stateMutability: "view",
    inputs: [
      { name: "offset", type: "uint256", internalType: "uint256" },
      { name: "limit", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "page",
        type: "tuple[]",
        internalType: "struct RailSplitPayXrp.Payment[]",
        components: [
          { name: "linkId", type: "bytes32", internalType: "bytes32" },
          { name: "payer", type: "address", internalType: "address" },
          { name: "amountWei", type: "uint256", internalType: "uint256" },
          { name: "priceUsdCents", type: "uint64", internalType: "uint64" },
          { name: "xrpUsdPrice", type: "uint256", internalType: "uint256" },
          { name: "quoteIssuedAt", type: "uint64", internalType: "uint64" },
          { name: "quoteValidUntil", type: "uint64", internalType: "uint64" },
          { name: "paidAt", type: "uint64", internalType: "uint64" },
        ],
      },
      { name: "slugs", type: "string[]", internalType: "string[]" },
      { name: "total", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    name: "merchantLinkCount",
    stateMutability: "view",
    inputs: [{ name: "merchant", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "function",
    name: "merchantLinkIdAt",
    stateMutability: "view",
    inputs: [
      { name: "merchant", type: "address", internalType: "address" },
      { name: "index", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "function",
    name: "quoteSigner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
  },
  {
    type: "function",
    name: "MAX_QUOTE_AGE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
  },
  {
    type: "function",
    name: "QUOTE_PRICE_DECIMALS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
  },
  {
    type: "event",
    name: "PaymentLinkCreated",
    anonymous: false,
    inputs: [
      { name: "linkId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "merchant", type: "address", indexed: true, internalType: "address" },
      { name: "slug", type: "string", indexed: false, internalType: "string" },
      { name: "title", type: "string", indexed: false, internalType: "string" },
      { name: "priceUsdCents", type: "uint64", indexed: false, internalType: "uint64" },
      { name: "expiresAt", type: "uint64", indexed: false, internalType: "uint64" },
    ],
  },
  {
    type: "event",
    name: "PaymentReceived",
    anonymous: false,
    inputs: [
      { name: "linkId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "merchant", type: "address", indexed: true, internalType: "address" },
      { name: "payer", type: "address", indexed: true, internalType: "address" },
      { name: "amountWei", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "priceUsdCents", type: "uint64", indexed: false, internalType: "uint64" },
      { name: "xrpUsdPrice", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "quoteIssuedAt", type: "uint64", indexed: false, internalType: "uint64" },
      { name: "quoteValidUntil", type: "uint64", indexed: false, internalType: "uint64" },
      { name: "paidAt", type: "uint64", indexed: false, internalType: "uint64" },
    ],
  },
  {
    type: "event",
    name: "PaymentLinkClosed",
    anonymous: false,
    inputs: [
      { name: "linkId", type: "bytes32", indexed: true, internalType: "bytes32" },
      { name: "merchant", type: "address", indexed: true, internalType: "address" },
    ],
  },
] as const;
